name: Ruby
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          persist-credentials: false
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb
        with:
          ruby-version: 2.6.10
      - name: Checks
        run: |
          gem install awesome_bot
          awesome_bot --allow-redirect --request-delay 1 README.md
