name: Ruby
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
      - name: Checks
        run: |
          gem install awesome_bot
          awesome_bot --allow-redirect --request-delay 1 README.md
  
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v0.8.0
    hooks:
      - id: zizmor
